name = "VortexDetection3D"
uuid = "db4f41e7-b2fa-44a1-a4de-921f1cd0ed8b"
authors = ["Tim Copland <timothy.copland98@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
